name: Build Enmity and Inject Rosiecord
on:
  push:
  workflow_dispatch:
  schedule:
    # weekly (every monday)
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build Enmity and Inject Rosiecord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main utils are installed
        id: core
        run: brew install coreutils ldid make

      - name: Run Main Script to Pull IPA and Patch Rosiecord
        id: build
        run: sh ./silly.sh
        
      - name: Retrieve version
        id: version
        run: |
          cd ./ipas
          echo __DISCORD_VERSION=$(ls | grep Discord | grep '[0-9]*' -oz | awk -F"\0" '{print $1 "_" $3}') >> $GITHUB_OUTPUT
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: rosiecord_${{ steps.version.outputs.__DISCORD_VERSION }}
          title: Rosiecord ${{ steps.version.outputs.__DISCORD_VERSION }}
          files: Dist/*.ipa
